### ISSUE TITLE
Connect Failed on Smart IPTV

### ISSUE THREAD

**Issue by haziqabgsapri** [freeview/iptv#10]
connection failed bila pakai apps smart iptv di tv samsung. semua channel xdpt play.

**Comment by akmalharith** [comment]
@haziqabgsapri Playlist ni optimized untuk Android TV sahaja.

**Comment by haziqabgsapri** [comment]
sepatutnya tak jadi masalah sbb menggunakan m3u playlist jugak

**Comment by akmalharith** [comment]
Sila semak balik playlist ni ada header `Referer` yang tak semua Smart TV support. 
```https://rtm1.secureswiftcontent.com/Origin01/ngrp:RTM1/chunklist_b2096000.m3u8|Referer=https://myklik.rtm.gov.my```

Boleh cuba remove header ni, tapi banyak source stream perlukan header yang valid untuk playable.

**Comment by haziqabgsapri** [comment]
okay baru tgk playlist td. baik saya cuba.

**Comment by haziqabgsapri** [comment]
dah cuba, xdpt pulak..boleh tak tlg buatkan playlist utk smart iptv?

**Comment by akmalharith** [comment]
Header `referer` perlu untuk streams playable. Tak boleh remove. Kena cari app smart TV yang boleh baca playlist saya. This is not an issue with the playlist, as it works with all Android TV players out there.
