### ISSUE TITLE
Malaysia IPTV

### ISSUE THREAD

**Issue by IMDNME5150** [freeview/iptv#14]
Malaysia Stream ain't working

**Comment by akmalharith** [comment]
What are you playing the M3U with? They're tested only with Android IPTV players such as, Tivimate, Kodi and Plex. Are you also located in Malaysia? Bear in mind some streams are geo-locked.

**Comment by IMDNME5150** [comment]
Me playing with VLC and GSE IPTV, I don't have any issues with the SG
Freeview M3u

Best Regards
Mohammed Adam'San Mohd Zain

**Comment by akmalharith** [comment]
They won't work with either of them. See the HTTP `referer` header that is included in the Malaysia IPTV playlist. VLC and GSE IPTV do not support it.
