### ISSUE TITLE
some malaysia channel cannot watch

### ISSUE THREAD

**Issue by terrible87** [freeview/iptv#16]
TV1
https://rtm1hd.secureswiftcontent.com/Origin01/ngrp:RTM1/chunklist_b1064000.m3u8|Referer=https://myklik.rtm.gov.my

TV2
https://rtm5hd.secureswiftcontent.com/Origin1/ngrp:RTM1/chunklist_b1064000.m3u8|Referer=https://myklik.rtm.gov.my

TV3
https://stream-03.sg1.dailymotion.com/sec(_9ERdFwnAbs1GZsc1AwhHUVb5SIfNiHrBecuCtsAhdc)/dm/3/x6qp375/d/live-3.m3u8|Referer=https://www.dailymotion.com/embed/video/k3GVzd2cWbveXyrApah

**Comment by khairulryan** [comment]
Those 3 channels are working as it should in kodi, tvirl (androidtv) and plex as tested personally by me. Wont work in perfect player or vlc as it needs user agent and geolocation header.

**Comment by akmalharith** [comment]
Still working fine. Make sure you're using the supported players to open them.
