### ISSUE TITLE
Updated Link for TRT World and Astro Naura

### ISSUE THREAD

**Issue by exodiver** [freeview/iptv#18]
Hi there, well done on your tv list and good job for the epg guide.

Notice that you are using a batch job to update your m3u8 file, so it will not be wise for me to do a pull request.

Anyway, the update link for TRT World (1080p): https://tv-trtworld.live.trt.com.tr/master_1080.m3u8

And if you are interested (since naura is in your epg list): 

#EXTINF:-1 tvg-group="MY/SG" " tvg-logo="https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/125_300.png",Naura
https://agplayback03.aotg-video.astro.com.my/CH2/master_NAURAGOSHOP4.m3u8

**Comment by akmalharith** [comment]
Thank you for the TRT World link. I've updated my playlist with 720p quality.

As for Astro links, I don't plan to include them as they're not technically public. I try to be within the legal boundaries as much as I can.
