### ISSUE TITLE
broken link for rtm and tv3

### ISSUE THREAD

**Issue by wabit037** [freeview/iptv#23]
greetings. im new here, very minimum knowledge in coding. however im interested to lean from you guys. noted few broken links for RTM and TV3.

ive tested few links which work for rtm1,rtm2,tv OKAY

https://rtm1hdmobile.secureswiftcontent.com/Origin01/ngrp:RTM1/chunklist_b1064000.m3u8
https://rtm5hdmobile.secureswiftcontent.com/Origin1/ngrp:RTM1/chunklist_b1064000.m3u8
https://rtm2hdmobile.secureswiftcontent.com/Origin02/ngrp:RTM2/chunklist_b2064000.m3u8

however, unable to fix m3u8 link for tv3.

**Comment by akmalharith** [comment]
What are you playing the links with? 
RTM, needs `Referer` HTTP header with the M3U8. Otherwise you can't play it.
TV3 has a session token. Each M3U8 will only last for a few hours at the most. Once expire, you will get a 403 error with the link.

**Comment by wabit037** [comment]
using vlc media player network stream

**Comment by akmalharith** [comment]
You cannot do that. The links will not work with VLC.

**Comment by wabit037** [comment]
i successfully stream via vlc (for rtm channel) using link as attached above

**Comment by akmalharith** [comment]
They are not made for VLC, some links might work, but some will not work, no matter what you do. You can see I have added the `Referer` headers to these links for example:
```
#EXTINF:-1 tvg-group="MY/SG" tvg-logo="https://freeview.github.io/iptv/logos/tv2.png",TV2
https://rtm5hd.secureswiftcontent.com/Origin1/ngrp:RTM1/chunklist_b1064000.m3u8|Referer=https://myklik.rtm.gov.my

#EXTINF:-1 tvg-group="MY/SG" tvg-logo="https://freeview.github.io/iptv/logos/tv3.png",TV3
https://stream-02.sg1.dailymotion.com/sec(_9ERdFwnAbs1GZsc1AwhHQqCYOYVPonD1hXRILo-gk8)/dm/3/x6qp375/d/live-3.m3u8|Referer=https://www.dailymotion.com/embed/video/k3GVzd2cWbveXyrApah
```

**Comment by wabit037** [comment]
> They are not made for VLC, some links might work, but some will not work, no matter what you do. You can see I have added the `Referer` headers to these links for example:
> ```
> #EXTINF:-1 tvg-group="MY/SG" tvg-logo="https://freeview.github.io/iptv/logos/tv2.png",TV2
> _https://rtm5hd.secureswiftcontent.com/Origin1/ngrp:RTM1/chunklist_b1064000.m3u8_|Referer=https://myklik.rtm.gov.my
> 
> #EXTINF:-1 tvg-group="MY/SG" tvg-logo="https://freeview.github.io/iptv/logos/tv3.png",TV3
> https://stream-02.sg1.dailymotion.com/sec(_9ERdFwnAbs1GZsc1AwhHQqCYOYVPonD1hXRILo-gk8)/dm/3/x6qp375/d/live-3.m3u8|Referer=https://www.dailymotion.com/embed/video/k3GVzd2cWbveXyrApah
> ```

what i meant i that, the code given for rtm channel ls are broken. ive tried this code which works

#EXTINF:-1 tvg-group="MY/SG" tvg-logo="https://freeview.github.io/iptv/logos/tv1.png",TV1
****https://rtm1hdmobile.secureswiftcontent.com/Origin01/ngrp:RTM1/chunklist_b1064000.m3u8|Referer=https://myklik.rtm.gov.my****

note the changes of link used

**Comment by akmalharith** [comment]
It's working fine mate.

**Comment by wabit037** [comment]
maybe because i used iptv apps ratjer than kodi. haha. by the way thanks for the explanation
