### ISSUE TITLE
TV1,2,3 not working

### ISSUE THREAD

**Issue by bdkminang** [freeview/iptv#24]
Hello...
Some of channel not working.

**Comment by akmalharith** [comment]
These channels are working fine for me. What player are you using? Also, make sure you have a player that automatically reloads the playlist. Some channels will expire in a few hours.

**Comment by bdkminang** [comment]
I use tivimate on mibox s. I also try on iptv pro on phone. Not working.

**Comment by akmalharith** [comment]
I am using Tivimate and works fine for me. So no problem with the links. How are you loading the playlist?

**Comment by bdkminang** [comment]
I try remote and add again its working now. Do you use premium tivimate? Free version dont have update the playlis.

**Comment by akmalharith** [comment]
Yes, you'll need a premium version of Tivimate for the auto-update feature. Otherwise you need to manually update it once the stream goes down.
