### ISSUE TITLE
Live streaming broken

### ISSUE THREAD

**Issue by sedna6633** [freeview/iptv#26]
All rtm link are broken right now.

**Comment by akmalharith** [comment]
I have no problems with RTM streams. What player are you using?

**Comment by sedna6633** [comment]
Iptv smarter
And perfect player

**Comment by akmalharith** [comment]
Both of these players do not support HTTP `Referer` header. You need to use other players which support it. For example in Android TV I use TiVimate. If you are using other Android devices you may have to use Kodi.

> Some info:
> * Streams are updated every 4 hour
> * EPG is updated daily at 01:00 with 3 days worth of data
> * Requires M3U players which support additional HTTP headers such as `Referer` and `User-Agent`
> * Sample in [Kodi](https://www.youtube.com/watch?v=u5BUG6iQHUc)
