### ISSUE TITLE
epg for trt world gone 

### ISSUE THREAD

**Issue by gfwfuckoff** [freeview/iptv#27]
thx any way，i'll have a try

**Comment by akmalharith** [comment]
It's never there. If you have the source, feel free to share any EPG sources.

**Comment by gfwfuckoff** [comment]
whoops😓  guess i was confused by other epg saurce , if i have a website provide trt world epg,but i don't know how to form it ,will it help?

**Comment by akmalharith** [comment]
Thanks. By having the website that is one of the EPG sources, but to form it into actual EPG we will need to scrape it. Unfortunately I am occupied with self development and work related matters, so I cannot spend time working with EPG at the moment. 

If you would like to help, you can start at http://www.webgrabplus.com/. This is the tool that I use to scrape EPGs.

**Comment by exodiver** [comment]
Hi all, if you are using webgrabplus to make your own epg, the epg for trt world can be grabbed from the uk-sky.com siteini.

**Comment by akmalharith** [comment]
https://github.com/freeview/iptv/commit/8ca8785f74ed82bfa184bca02749f0e5303fa35a
