### ISSUE TITLE
new channel m3u

### ISSUE THREAD

**Issue by hamba-allah786** [freeview/iptv#29]
hi good day.

I had found a website (https://iptvcat.com/malaysia) that provide url for m3u8.

1. Astro Go Shop (https://agplayback03.aotg-video.astro.com.my/CH1/master_GOSHOP.m3u8?checkedby:iptvcat.com)

2. Astro Go Shop 2 (https://agplayback03.aotg-video.astro.com.my/CH3/master_GOSHOP3.m3u8?checkedby:iptvcat.com)

3. Astro Go Shop Chinese (https://agplayback03.aotg-video.astro.com.my/CH2/master_GOSHOP2.m3u8?checkedby:iptvcat.com)

4. Naura (https://agplayback03.aotg-video.astro.com.my/CH2/master_NAURAGOSHOP4.m3u8?checkedby:iptvcat.com)

5. TV Ikim (http://edge.vediostream.com:80/abr/tvikim/live/tvikim_source/chunks.m3u8?checkedby:iptvcat.com)

Thanks

**Comment by akmalharith** [comment]
Astro streams are not public therefore considered illegal so will not be added. TV Ikim will be added soon thanks.
