### ISSUE TITLE
TV local 

### ISSUE THREAD

**Issue by arexsekerat** [freeview/iptv#30]
TV3 tak boleh streaming bos.

**Comment by akmalharith** [comment]
Pakai player apa? Ada baca Readme tak? TV3 okay jer. Maybe player tak update stream. 

> **Additional info:
Streams are updated every 4 hour. Make sure the URLs are reloaded.
EPG is updated daily at 01:00 with 7 days worth of data
Requires M3U players which support additional HTTP headers such as Referer and User-Agent, E.g Tivimate, TVirl, most IPTV addons in Kodi
Sample in Kodi**

**Comment by arexsekerat** [comment]
Guna player GSE IPTV pada ios 9.3.

**Comment by akmalharith** [comment]
Tak support. Playlist ni hanya untuk Android TV dan hanya boleh play dengan players seperti Tivimate, TVIrl dan Kodi.

**Comment by nextinnova11** [comment]
HOB x boleh dapat kah?
