### ISSUE TITLE
Channel is unavailable and this pops up!

### ISSUE THREAD

**Issue by YueChan** [freeview/iptv#33]
Hi,

Thanks for your playlist. When I play channel 5, it pops up the following: This TV model does not support the content protection requirement for this programme. To view this programme, please use one of the supported devices listed on mewatch.sg/help/.

What could be the issue?  

Thanks,

Yue Chan

**Comment by akmalharith** [comment]
This is a content protection mechanism by MeWatch. Some shows cannot be streamed due to copyrights or something.

**Comment by YueChan** [comment]
Thanks, it sometimes happens on Channel 5, Channel 8 though.

**Comment by exodiver** [comment]
It is just a placeholder for the station refuse to stream the show. Nothing to do with actual drm. You will be need to find someone who is willing to share his tvendhead stream of singapore tv program.

**Comment by akmalharith** [comment]
> It is just a placeholder for the station refuse to stream the show. Nothing to do with actual drm. You will be need to find someone who is willing to share his tvendhead stream of singapore tv program.

I don't share re-streamed links here.
