### ISSUE TITLE
Epg Not working on Tivimate

### ISSUE THREAD

**Issue by Arsyad1105** [freeview/iptv#44]
Epg is not loaded in tivimate.

**Comment by akmalharith** [comment]
Check your URL. It is updated to a GZip now.

**Comment by Arsyad1105** [comment]
I have update link before but it not load the epg.

**Comment by akmalharith** [comment]
Sorry, it is not reproducible on my side, so there is nothing wrong with my EPG. 

I would suggest try clearing the EPG before updating it again. If that does not help please seek assistance from [Tivimate](https://www.reddit.com/r/TiviMate/).
