### ISSUE TITLE
TV3 not working on Kodi Mi Box S

### ISSUE THREAD

**Issue by amiladycintosh** [freeview/iptv#47]
Hi, it works fine on my phone using Kodi. Only issue with my Mi Box S, since this week could not watch TV3, NTV7, TV8, TV9 & Drama Sangat. But it works totally fine on my phone. My Mi Box S is using Kodi too. No idea why. 😅

**Comment by akmalharith** [comment]
I can't really guess as I am not using Kodi. Are you using URL or are you manually uploading the M3U file?

**Comment by amiladycintosh** [comment]
Oh. Both my phone and Mi Box s using URL. Any other recommended app to use for mi box s?

**Comment by afiz-tm** [comment]
I believed Kodi doesn't have 'auto-update' feature for m3u playlist URL (maybe I'm wrong). And some of the streaming URL is dynamically changed and keep changing, eg Media Prima. 

So for Kodi, either you restart the Kodi app (also please set the playlist to 'do not cache') OR if you don;t want to restart Kodi, you also can disable-and-enable the PVR Live TV add-on

**Comment by afiz-tm** [comment]
> Oh. Both my phone and Mi Box s using URL. Any other recommended app to use for mi box s?

Please read the README file.

**Comment by amiladycintosh** [comment]
It works! Just need to shutdown Kodi and run again, now can watch back tv3 and others! Thank you!
