### ISSUE TITLE
EPG for Drama Sangat

### ISSUE THREAD

**Issue by akmalharith** [freeview/iptv#5]
No source to scrape yet

**Comment by weareblahs** [comment]
The only EPG data can be found here: https://www.tonton.com.my/liveChannel?titleId=ds1_channel

Waiting for someone to scrape it.

**Comment by akmalharith** [comment]
@weareblahs I'm working on it, may take a few weeks.

**Comment by akmalharith** [comment]
Draft work:
```
Request URL: https://prod-api.tonton.com.my/tonton/v0.3/assets/eventlist
Request Method: POST
```

**Comment by onecai813** [comment]
can’t open on pastebin?

**Comment by Badlish** [comment]
Need m3u url for malaysia, singapore and indonesia channels?

I used IGBOX but suddenly all iptv channels inactivated.

Can anyone help pls?

Badlish
