### ISSUE TITLE
Anything idea to use the data here? webgrabplus

### ISSUE THREAD

**Issue by shiroamada** [freeview/iptv#6]
http://www.webgrabplus.com/epg-channels#s121

**Comment by akmalharith** [comment]
@shiroamada, have you tried with the default astro.com.my site ini?

**Comment by shiroamada** [comment]
I tried http://api-epg.astro.com.my/api/metadata
only able to get all channel, other can't get data, not sure I understand the API enough or not. Can you get the data from the link?

**Comment by akmalharith** [comment]
@shiroamada Actually one easy way you can do is that you can load the EPG page itself and monitor the network requests. You can see what endpoints are in use to load the EPG data.
![astro-epg](https://user-images.githubusercontent.com/22504259/72199596-0fdc3b80-3479-11ea-9062-ce37fac32244.png)
