### ISSUE TITLE
TV Alhijrah down

### ISSUE THREAD

**Issue by akmalharith** [freeview/iptv#7]
Source is offline https://alhijrahmedia.com/tv-alhijrah-live-streaming/

**Comment by exodiver** [comment]
Back again at: https://www.youtube.com/watch?v=jxNk9tQJhSw 

They just change their youtube channel every few week.

**Comment by akmalharith** [comment]
Down since 20/1/2019 Youtube suspended their official stream

**Comment by akmalharith** [comment]
Stream offline again https://www.youtube.com/channel/UCa5Go98H_EQOqwjYgx5-suw/live

**Comment by akmalharith** [comment]
> Back again at: https://www.youtube.com/watch?v=jxNk9tQJhSw
> 
> They just change their youtube channel every few week.

YouTube channel is always same. You can view any live stream by just adding `/live` at the end of the URL.
