### ISSUE TITLE
Wrong EPG info

### ISSUE THREAD

**Issue by weareblahs** [freeview/iptv#9]
Wrong EPG Info for Malaysia TV. Some channels have the same EPG schedule.

**Comment by akmalharith** [comment]
@weareblahs Do you mind sharing what exact channels are they, and what programmers are being shown for these channels? My script last updated the EPG last night 20200107000000, on my side it has been working fine.

**Comment by akmalharith** [comment]
I would advise you to check if you are always reloading the EPG source. You need a player capable to auto update them.
